
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: webserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: webserver
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: webserver
      spec:
        containers:
        - image: nginxinc/nginx-unprivileged
          name: webserver
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: webserver
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: webserver
  status:
    loadBalancer: {}
kind: List
metadata: {}
